[webservers]
servidor-01 ansible_host=COLE_O_IP_01_AQUI
servidor-02 ansible_host=COLE_O_IP_02_AQUI

[webservers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=./labsuser.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'